name: Build FernFlower

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Compile all .java files
      run: |
        mkdir out
        find src -name "*.java" > sources.txt
        javac -d out @sources.txt

    - name: Package into fernflower.jar
      run: |
        cd out
        echo "Main-Class: org.jetbrains.java.decompiler.main.decompiler.ConsoleDecompiler" > manifest.txt
        jar cfm ../fernflower.jar manifest.txt *

    - name: Upload fernflower.jar
      uses: actions/upload-artifact@v4
      with:
        name: fernflower
        path: fernflower.jar
