name: Build FernFlower

on:
  workflow_dispatch: # Cho phép build thủ công
  push:              # Tự động build mỗi lần đẩy code

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Compile FernFlower
      run: |
        mkdir out
        javac -d out -cp src src/org/jetbrains/java/decompiler/main/externIF/*.java src/org/jetbrains/java/decompiler/main/*.java src/org/jetbrains/java/decompiler/modules/*.java src/org/jetbrains/java/decompiler/modules/decompiler/*.java src/org/jetbrains/java/decompiler/modules/struct/*.java src/org/jetbrains/java/decompiler/runtime/*.java src/org/jetbrains/java/decompiler/util/*.java

    - name: Package into fernflower.jar
      run: |
        cd out
        jar cfe ../fernflower.jar org.jetbrains.java.decompiler.main.decompiler.ConsoleDecompiler *

    - name: Upload fernflower.jar
      uses: actions/upload-artifact@v4
      with:
        name: fernflower
        path: fernflower.jar
